#' Computes a Polynomial Function ( a formula )
#' able to generate from the X values received, the correspondent Y values received
#'
#' @description
#' Computes a Generating Function able to generate the expected Outputs
#'
#' @param X A vector of numeric inputs
#' @param Y A vector of numeric outputs that must be generated by the returned function
#' @returns A function able to generate from the X values received, the correspondent Y values received
#'
#' @export
#'
#' @examples
#' fp = minifunctions::getfunctionpolynom(1:3,c(3,7,21))
#' for ( i in 1:10 ) print(fp(i))
getfunctionpolynom = function(X,Y) {
  # X = 1:3
  # Y = c(6,15,28)

  options(digits = 22)
  n = length(X)
  A = NULL
  for ( x in X ) {
    v = vector()
    for ( j in 1:n ) v = c(v, x^(n-j))
    A = rbind(A,v)
  }

  factors = solve(gmp::as.bigq(A), Y)

  f = ""
  solution = "f = function(n) "
  for ( i in 1:n ) if (factors[i] != 0) solution = paste0(solution," + ",factors[i]," * n^",n-i)
  # print(solution)
  eval(parse(text = paste(solution, sep='')))
  return( f )
}

